version: 2
workflows:
  version: 2
  ci:
    jobs:
    - sea
    - invoicing_app
jobs:
  sea:
    docker:
      - image: circleci/elixir:1.7.4
      - image: circleci/postgres:10.6-alpine
    environment:
      - MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --warnings-as-errors --force
      - run: mix format --check-formatted --dry-run
      - run: mix test
      - store_test_results:
          path: /tmp/sea-elixir-test-results
      - run: mix credo
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)
  invoicing_app:
    docker:
      - image: circleci/elixir:1.7.4
    environment:
      - MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: cd examples/invoicing_app
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test
